Route List
+--------------------------------------------+-------------------------------------------------+--------+-------------------------------------------------+
| Rule                                       | Route                                           | Method | Name                                            |
+--------------------------------------------+-------------------------------------------------+--------+-------------------------------------------------+
|                                            | Index/index                                     | get    | Index/index                                     |
|                                            | IndexController/index                           | get    | IndexController/index                           |
| auth/refresh                               | AuthController/refresh                          | post   | AuthController/refresh                          |
| auth/login                                 | AuthController/login                            | post   | AuthController/login                            |
| auth/register                              | AuthController/register                         | post   | AuthController/register                         |
| system/status                              | SystemController/status                         | get    | SystemController/status                         |
| skus/select                                | ProductController/skuSelect                     | get    | ProductController/skuSelect                     |
| dashboard/overview                         | DashboardController/overview                    | get    | DashboardController/overview                    |
| dashboard/statistics                       | DashboardController/statistics                  | get    | DashboardController/statistics                  |
| dashboard/alerts                           | DashboardController/alerts                      | get    | DashboardController/alerts                      |
| dashboard/quick-actions                    | DashboardController/quickActions                | get    | DashboardController/quickActions                |
| auth/logout                                | AuthController/logout                           | post   | AuthController/logout                           |
| auth/userinfo                              | AuthController/userinfo                         | get    | AuthController/userinfo                         |
| auth/profile                               | AuthController/updateProfile                    | put    | AuthController/updateProfile                    |
| auth/password                              | AuthController/changePassword                   | put    | AuthController/changePassword                   |
| products                                   | ProductController/index                         | get    | ProductController/index                         |
| products                                   | ProductController/save                          | post   | ProductController/save                          |
| products/<id>                              | ProductController/read                          | get    | ProductController/read                          |
| products/<id>                              | ProductController/update                        | put    | ProductController/update                        |
| products/<id>                              | ProductController/delete                        | delete | ProductController/delete                        |
| products/batch                             | ProductController/batch                         | post   | ProductController/batch                         |
| products/search/select                     | ProductController/selectSearch                  | get    | ProductController/selectSearch                  |
| products/export                            | ProductController/export                        | get    | ProductController/export                        |
| products/import                            | ProductController/import                        | post   | ProductController/import                        |
| products/<id>/aggregate                    | ProductController/aggregate                     | get    | ProductController/aggregate                     |
| products/<id>/aggregate                    | ProductController/updateAggregate               | put    | ProductController/updateAggregate               |
| products/aggregate                         | ProductController/saveAggregate                 | post   | ProductController/saveAggregate                 |
| skus                                       | ProductController/skuIndex                      | get    | ProductController/skuIndex                      |
| skus                                       | ProductController/skuSave                       | post   | ProductController/skuSave                       |
| skus/<id>                                  | ProductController/skuRead                       | get    | ProductController/skuRead                       |
| skus/<id>                                  | ProductController/skuUpdate                     | put    | ProductController/skuUpdate                     |
| skus/<id>                                  | ProductController/skuDelete                     | delete | ProductController/skuDelete                     |
| skus/batch                                 | ProductController/skuBatchSave                  | post   | ProductController/skuBatchSave                  |
| skus/batch                                 | ProductController/skuBatchDelete                | delete | ProductController/skuBatchDelete                |
| skus/batch/<product_id>                    | ProductController/skuBatchUpdate                | put    | ProductController/skuBatchUpdate                |
| skus/product/<product_id>                  | ProductController/skuByProduct                  | get    | ProductController/skuByProduct                  |
| categories                                 | CategoryController/index                        | get    | CategoryController/index                        |
| categories                                 | CategoryController/save                         | post   | CategoryController/save                         |
| categories/<id>                            | CategoryController/read                         | get    | CategoryController/read                         |
| categories/<id>                            | CategoryController/update                       | put    | CategoryController/update                       |
| categories/<id>                            | CategoryController/delete                       | delete | CategoryController/delete                       |
| categories/tree                            | CategoryController/tree                         | get    | CategoryController/tree                         |
| categories/options                         | CategoryController/options                      | get    | CategoryController/options                      |
| brands                                     | BrandController/index                           | get    | BrandController/index                           |
| brands                                     | BrandController/save                            | post   | BrandController/save                            |
| brands/options                             | BrandController/options                         | get    | BrandController/options                         |
| brands/<id>                                | BrandController/read                            | get    | BrandController/read                            |
| brands/<id>                                | BrandController/update                          | put    | BrandController/update                          |
| brands/<id>                                | BrandController/delete                          | delete | BrandController/delete                          |
| customers                                  | CustomerController/index                        | get    | CustomerController/index                        |
| customers                                  | CustomerController/save                         | post   | CustomerController/save                         |
| customers/<id>                             | CustomerController/read                         | get    | CustomerController/read                         |
| customers/<id>                             | CustomerController/update                       | put    | CustomerController/update                       |
| customers/<id>                             | CustomerController/delete                       | delete | CustomerController/delete                       |
| customers/search/select                    | CustomerController/selectSearch                 | get    | CustomerController/selectSearch                 |
| customers/<id>/arrears                     | CustomerController/arrears                      | get    | CustomerController/arrears                      |
| customers/<id>/arrears                     | CustomerController/updateArrears                | post   | CustomerController/updateArrears                |
| customers/statistics                       | CustomerController/statistics                   | get    | CustomerController/statistics                   |
| suppliers                                  | SupplierController/index                        | get    | SupplierController/index                        |
| suppliers                                  | SupplierController/save                         | post   | SupplierController/save                         |
| suppliers/<id>                             | SupplierController/read                         | get    | SupplierController/read                         |
| suppliers/<id>                             | SupplierController/update                       | put    | SupplierController/update                       |
| suppliers/<id>                             | SupplierController/delete                       | delete | SupplierController/delete                       |
| suppliers/search/select                    | SupplierController/selectSearch                 | get    | SupplierController/selectSearch                 |
| suppliers/<id>/arrears                     | SupplierController/arrears                      | get    | SupplierController/arrears                      |
| suppliers/<id>/arrears                     | SupplierController/updateArrears                | post   | SupplierController/updateArrears                |
| warehouses                                 | WarehouseController/index                       | get    | WarehouseController/index                       |
| warehouses                                 | WarehouseController/save                        | post   | WarehouseController/save                        |
| warehouses/<id>                            | WarehouseController/read                        | get    | WarehouseController/read                        |
| warehouses/<id>                            | WarehouseController/update                      | put    | WarehouseController/update                      |
| warehouses/<id>                            | WarehouseController/delete                      | delete | WarehouseController/delete                      |
| warehouses/options                         | WarehouseController/options                     | get    | WarehouseController/options                     |
| warehouses/<id>/statistics                 | WarehouseController/statistics                  | get    | WarehouseController/statistics                  |
| purchase/orders                            | PurchaseOrderController/index                   | get    | PurchaseOrderController/index                   |
| purchase/orders                            | PurchaseOrderController/save                    | post   | PurchaseOrderController/save                    |
| purchase/orders/<id>                       | PurchaseOrderController/read                    | get    | PurchaseOrderController/read                    |
| purchase/orders/<id>                       | PurchaseOrderController/update                  | put    | PurchaseOrderController/update                  |
| purchase/orders/<id>                       | PurchaseOrderController/delete                  | delete | PurchaseOrderController/delete                  |
| purchase/orders/<id>/audit                 | PurchaseOrderController/audit                   | post   | PurchaseOrderController/audit                   |
| purchase/orders/<id>/cancel                | PurchaseOrderController/cancel                  | post   | PurchaseOrderController/cancel                  |
| purchase/orders/<id>/complete              | PurchaseOrderController/complete                | post   | PurchaseOrderController/complete                |
| purchase/orders/<id>/items                 | PurchaseOrderController/items                   | get    | PurchaseOrderController/items                   |
| purchase/orders/<id>/items                 | PurchaseOrderController/addItem                 | post   | PurchaseOrderController/addItem                 |
| purchase/orders/<id>/items/<item_id>       | PurchaseOrderController/updateItem              | put    | PurchaseOrderController/updateItem              |
| purchase/orders/<id>/items/<item_id>       | PurchaseOrderController/deleteItem              | delete | PurchaseOrderController/deleteItem              |
| purchase/orders/<id>/returns               | PurchaseOrderController/returns                 | get    | PurchaseOrderController/returns                 |
| purchase/orders/<id>/returnable_items      | PurchaseOrderController/returnableItems         | get    | PurchaseOrderController/returnableItems         |
| purchase/stocks                            | PurchaseStockController/index                   | get    | PurchaseStockController/index                   |
| purchase/stocks                            | PurchaseStockController/save                    | post   | PurchaseStockController/save                    |
| purchase/stocks/<id>                       | PurchaseStockController/read                    | get    | PurchaseStockController/read                    |
| purchase/stocks/<id>                       | PurchaseStockController/update                  | put    | PurchaseStockController/update                  |
| purchase/stocks/<id>                       | PurchaseStockController/delete                  | delete | PurchaseStockController/delete                  |
| purchase/stocks/<id>/audit                 | PurchaseStockController/audit                   | post   | PurchaseStockController/audit                   |
| purchase/stocks/<id>/cancel                | PurchaseStockController/cancel                  | post   | PurchaseStockController/cancel                  |
| purchase/stocks/<id>/items                 | PurchaseStockController/items                   | get    | PurchaseStockController/items                   |
| purchase/stocks/<id>/items                 | PurchaseStockController/addItem                 | post   | PurchaseStockController/addItem                 |
| purchase/stocks/<id>/items/<item_id>       | PurchaseStockController/updateItem              | put    | PurchaseStockController/updateItem              |
| purchase/stocks/<id>/items/<item_id>       | PurchaseStockController/deleteItem              | delete | PurchaseStockController/deleteItem              |
| purchase/stocks/check_availability/<id>    | PurchaseStockController/checkStockAvailability  | get    | PurchaseStockController/checkStockAvailability  |
| purchase/stocks/by_order/<order_id>        | PurchaseStockController/getStocksByOrderId      | get    | PurchaseStockController/getStocksByOrderId      |
| purchase/stocks/<id>/returns               | PurchaseStockController/returns                 | get    | PurchaseStockController/returns                 |
| sale/orders                                | SaleOrderController/index                       | get    | SaleOrderController/index                       |
| sale/orders                                | SaleOrderController/save                        | post   | SaleOrderController/save                        |
| sale/orders/<id>                           | SaleOrderController/read                        | get    | SaleOrderController/read                        |
| sale/orders/<id>                           | SaleOrderController/update                      | put    | SaleOrderController/update                      |
| sale/orders/<id>                           | SaleOrderController/delete                      | delete | SaleOrderController/delete                      |
| sale/orders/<id>/audit                     | SaleOrderController/audit                       | post   | SaleOrderController/audit                       |
| sale/orders/<id>/cancel                    | SaleOrderController/cancel                      | post   | SaleOrderController/cancel                      |
| sale/orders/<id>/complete                  | SaleOrderController/complete                    | post   | SaleOrderController/complete                    |
| sale/orders/<id>/items                     | SaleOrderController/items                       | get    | SaleOrderController/items                       |
| sale/orders/<id>/items                     | SaleOrderController/addItem                     | post   | SaleOrderController/addItem                     |
| sale/orders/<id>/items/<item_id>           | SaleOrderController/updateItem                  | put    | SaleOrderController/updateItem                  |
| sale/orders/<id>/items/<item_id>           | SaleOrderController/deleteItem                  | delete | SaleOrderController/deleteItem                  |
| sale/orders/<id>/returns                   | SaleOrderController/returns                     | get    | SaleOrderController/returns                     |
| sale/orders/<id>/returnable_items          | SaleOrderController/returnableItems             | get    | SaleOrderController/returnableItems             |
| sale/stocks                                | SaleStockController/index                       | get    | SaleStockController/index                       |
| sale/stocks                                | SaleStockController/save                        | post   | SaleStockController/save                        |
| sale/stocks/<id>                           | SaleStockController/read                        | get    | SaleStockController/read                        |
| sale/stocks/<id>                           | SaleStockController/update                      | put    | SaleStockController/update                      |
| sale/stocks/<id>                           | SaleStockController/delete                      | delete | SaleStockController/delete                      |
| sale/stocks/<id>/audit                     | SaleStockController/audit                       | post   | SaleStockController/audit                       |
| sale/stocks/<id>/cancel                    | SaleStockController/cancel                      | post   | SaleStockController/cancel                      |
| sale/stocks/<id>/items                     | SaleStockController/items                       | get    | SaleStockController/items                       |
| sale/stocks/<id>/items                     | SaleStockController/addItem                     | post   | SaleStockController/addItem                     |
| sale/stocks/<id>/items/<item_id>           | SaleStockController/updateItem                  | put    | SaleStockController/updateItem                  |
| sale/stocks/<id>/items/<item_id>           | SaleStockController/deleteItem                  | delete | SaleStockController/deleteItem                  |
| sale/stocks/<id>/complete                  | SaleStockController/complete                    | post   | SaleStockController/complete                    |
| sale/stocks/<id>/returns                   | SaleStockController/returns                     | get    | SaleStockController/returns                     |
| returns                                    | ReturnOrderController/index                     | get    | ReturnOrderController/index                     |
| returns                                    | ReturnOrderController/save                      | post   | ReturnOrderController/save                      |
| returns/<id>                               | ReturnOrderController/read                      | get    | ReturnOrderController/read                      |
| returns/<id>                               | ReturnOrderController/update                    | put    | ReturnOrderController/update                    |
| returns/<id>                               | ReturnOrderController/delete                    | delete | ReturnOrderController/delete                    |
| returns/<id>/audit                         | ReturnOrderController/audit                     | post   | ReturnOrderController/audit                     |
| returns/<id>/cancel                        | ReturnOrderController/cancel                    | post   | ReturnOrderController/cancel                    |
| returns/<id>/complete                      | ReturnOrderController/complete                  | post   | ReturnOrderController/complete                  |
| returns/<id>/items                         | ReturnOrderController/items                     | get    | ReturnOrderController/items                     |
| returns/<id>/items                         | ReturnOrderController/addItem                   | post   | ReturnOrderController/addItem                   |
| returns/<id>/items/<item_id>               | ReturnOrderController/updateItem                | put    | ReturnOrderController/updateItem                |
| returns/<id>/items/<item_id>               | ReturnOrderController/deleteItem                | delete | ReturnOrderController/deleteItem                |
| returns/<id>/stocks                        | ReturnOrderController/stocks                    | get    | ReturnOrderController/stocks                    |
| returns/<id>/create_stock                  | ReturnOrderController/createStock               | post   | ReturnOrderController/createStock               |
| return_stocks                              | ReturnStockController/index                     | get    | ReturnStockController/index                     |
| return_stocks                              | ReturnStockController/save                      | post   | ReturnStockController/save                      |
| return_stocks/<id>                         | ReturnStockController/read                      | get    | ReturnStockController/read                      |
| return_stocks/<id>                         | ReturnStockController/update                    | put    | ReturnStockController/update                    |
| return_stocks/<id>                         | ReturnStockController/delete                    | delete | ReturnStockController/delete                    |
| return_stocks/<id>/audit                   | ReturnStockController/audit                     | post   | ReturnStockController/audit                     |
| return_stocks/<id>/cancel                  | ReturnStockController/cancel                    | post   | ReturnStockController/cancel                    |
| return_stocks/<id>/items                   | ReturnStockController/items                     | get    | ReturnStockController/items                     |
| return_stocks/<id>/items                   | ReturnStockController/addItem                   | post   | ReturnStockController/addItem                   |
| return_stocks/<id>/items/<item_id>         | ReturnStockController/deleteItem                | delete | ReturnStockController/deleteItem                |
| stocks/skus                                | StockController/skuIndex                        | get    | StockController/skuIndex                        |
| stocks/skus/<id>/warehouses                | StockController/skuWarehouse                    | get    | StockController/skuWarehouse                    |
| stocks/skus/<id>                           | StockController/skuUpdate                       | put    | StockController/skuUpdate                       |
| stocks/skus/warning                        | StockController/skuWarning                      | get    | StockController/skuWarning                      |
| stocks/skus/statistics                     | StockController/skuStatistics                   | get    | StockController/skuStatistics                   |
| stock/takes                                | StockTakeController/index                       | get    | StockTakeController/index                       |
| stock/takes                                | StockTakeController/save                        | post   | StockTakeController/save                        |
| stock/takes/<id>                           | StockTakeController/read                        | get    | StockTakeController/read                        |
| stock/takes/<id>                           | StockTakeController/update                      | put    | StockTakeController/update                      |
| stock/takes/<id>                           | StockTakeController/delete                      | delete | StockTakeController/delete                      |
| stock/takes/<id>/audit                     | StockTakeController/audit                       | post   | StockTakeController/audit                       |
| stock/takes/<id>/complete                  | StockTakeController/complete                    | post   | StockTakeController/complete                    |
| stock/takes/<id>/cancel                    | StockTakeController/cancel                      | post   | StockTakeController/cancel                      |
| stock/takes/<id>/items                     | StockTakeController/items                       | get    | StockTakeController/items                       |
| stock/takes/<id>/items                     | StockTakeController/addItem                     | post   | StockTakeController/addItem                     |
| stock/takes/<id>/items/<item_id>           | StockTakeController/updateItem                  | put    | StockTakeController/updateItem                  |
| stock/takes/<id>/items/<item_id>           | StockTakeController/deleteItem                  | delete | StockTakeController/deleteItem                  |
| stock/transfers                            | StockTransferController/index                   | get    | StockTransferController/index                   |
| stock/transfers                            | StockTransferController/save                    | post   | StockTransferController/save                    |
| stock/transfers/<id>                       | StockTransferController/read                    | get    | StockTransferController/read                    |
| stock/transfers/<id>                       | StockTransferController/update                  | put    | StockTransferController/update                  |
| stock/transfers/<id>                       | StockTransferController/delete                  | delete | StockTransferController/delete                  |
| stock/transfers/<id>/audit                 | StockTransferController/audit                   | post   | StockTransferController/audit                   |
| stock/transfers/<id>/transfer              | StockTransferController/transfer                | post   | StockTransferController/transfer                |
| stock/transfers/<id>/complete              | StockTransferController/complete                | post   | StockTransferController/complete                |
| stock/transfers/<id>/cancel                | StockTransferController/cancel                  | post   | StockTransferController/cancel                  |
| stock/transfers/<id>/items                 | StockTransferController/items                   | get    | StockTransferController/items                   |
| stock/transfers/<id>/items                 | StockTransferController/addItem                 | post   | StockTransferController/addItem                 |
| stock/transfers/<id>/items/<item_id>       | StockTransferController/updateItem              | put    | StockTransferController/updateItem              |
| stock/transfers/<id>/items/<item_id>       | StockTransferController/deleteItem              | delete | StockTransferController/deleteItem              |
| financial/records                          | FinancialRecordController/index                 | get    | FinancialRecordController/index                 |
| financial/records                          | FinancialRecordController/save                  | post   | FinancialRecordController/save                  |
| financial/records/<id>                     | FinancialRecordController/read                  | get    | FinancialRecordController/read                  |
| financial/records/<id>                     | FinancialRecordController/update                | put    | FinancialRecordController/update                |
| financial/records/<id>                     | FinancialRecordController/delete                | delete | FinancialRecordController/delete                |
| financial/records/categories               | FinancialRecordController/categories            | get    | FinancialRecordController/categories            |
| financial/records/statistics               | FinancialRecordController/statistics            | get    | FinancialRecordController/statistics            |
| account/records                            | AccountRecordController/index                   | get    | AccountRecordController/index                   |
| account/records/summary                    | AccountRecordController/summary                 | get    | AccountRecordController/summary                 |
| account/records/<id>/pay                   | AccountRecordController/pay                     | post   | AccountRecordController/pay                     |
| account/records/receivable                 | AccountRecordController/receivable              | get    | AccountRecordController/receivable              |
| account/records/payable                    | AccountRecordController/payable                 | get    | AccountRecordController/payable                 |
| account/records/statistics                 | AccountRecordController/statistics              | get    | AccountRecordController/statistics              |
| account/settlement                         | AccountSettlementController/index               | get    | AccountSettlementController/index               |
| account/settlement                         | AccountSettlementController/create              | post   | AccountSettlementController/create              |
| account/settlement/<id>                    | AccountSettlementController/read                | get    | AccountSettlementController/read                |
| account/settlement/batch                   | AccountSettlementController/batchCreate         | post   | AccountSettlementController/batchCreate         |
| account/settlement/account/<accountId>     | AccountSettlementController/getByAccountId      | get    | AccountSettlementController/getByAccountId      |
| account/settlement/financial/<financialId> | AccountSettlementController/getByFinancialId    | get    | AccountSettlementController/getByFinancialId    |
| account/settlement/settleable              | AccountSettlementController/getSettableAccounts | get    | AccountSettlementController/getSettableAccounts |
| account/settlement/statistics              | AccountSettlementController/getStatistics       | get    | AccountSettlementController/getStatistics       |
| account/settlement/cancel/<id>             | AccountSettlementController/cancel              | post   | AccountSettlementController/cancel              |
| financial/reports/profit                   | FinancialReportController/profit                | get    | FinancialReportController/profit                |
| financial/reports/cashflow                 | FinancialReportController/cashflow              | get    | FinancialReportController/cashflow              |
| financial/reports/sales                    | FinancialReportController/sales                 | get    | FinancialReportController/sales                 |
| financial/reports/purchase                 | FinancialReportController/purchase              | get    | FinancialReportController/purchase              |
| financial/reports/inventory                | FinancialReportController/inventory             | get    | FinancialReportController/inventory             |
| users                                      | UserController/index                            | get    | UserController/index                            |
| users                                      | UserController/save                             | post   | UserController/save                             |
| users/<id>                                 | UserController/read                             | get    | UserController/read                             |
| users/<id>                                 | UserController/update                           | put    | UserController/update                           |
| users/<id>                                 | UserController/delete                           | delete | UserController/delete                           |
| users/<id>/status                          | UserController/setStatus                        | post   | UserController/setStatus                        |
| users/<id>/reset-password                  | UserController/resetPassword                    | post   | UserController/resetPassword                    |
| roles                                      | RoleController/index                            | get    | RoleController/index                            |
| roles                                      | RoleController/save                             | post   | RoleController/save                             |
| roles/<id>                                 | RoleController/read                             | get    | RoleController/read                             |
| roles/<id>                                 | RoleController/update                           | put    | RoleController/update                           |
| roles/<id>                                 | RoleController/delete                           | delete | RoleController/delete                           |
| roles/options                              | RoleController/options                          | get    | RoleController/options                          |
| roles/permissions                          | RoleController/permissions                      | get    | RoleController/permissions                      |
| system/configs                             | SystemController/configs                        | get    | SystemController/configs                        |
| system/configs                             | SystemController/saveConfigs                    | post   | SystemController/saveConfigs                    |
| system/configs/<group>                     | SystemController/configGroup                    | get    | SystemController/configGroup                    |
| system/info                                | SystemController/info                           | get    | SystemController/info                           |
| system/logs                                | SystemController/logs                           | get    | SystemController/logs                           |
| system/logs                                | SystemController/clearLogs                      | delete | SystemController/clearLogs                      |
| utils/number/generate/<type>               | UtilsController/generateNumber                  | get    | UtilsController/generateNumber                  |
| utils/upload/image                         | UtilsController/uploadImage                     | post   | UtilsController/uploadImage                     |
| utils/upload/file                          | UtilsController/uploadFile                      | post   | UtilsController/uploadFile                      |
| utils/regions                              | UtilsController/regions                         | get    | UtilsController/regions                         |
| utils/units                                | UtilsController/units                           | get    | UtilsController/units                           |
| analytics/sales                            | AnalyticsController/sales                       | get    | AnalyticsController/sales                       |
| analytics/purchase                         | AnalyticsController/purchase                    | get    | AnalyticsController/purchase                    |
| analytics/inventory                        | AnalyticsController/inventory                   | get    | AnalyticsController/inventory                   |
| analytics/financial                        | AnalyticsController/financial                   | get    | AnalyticsController/financial                   |
| analytics/customer                         | AnalyticsController/customer                    | get    | AnalyticsController/customer                    |
| analytics/supplier                         | AnalyticsController/supplier                    | get    | AnalyticsController/supplier                    |
| test                                       | TestController/index                            | get    | TestController/index                            |
| debug/routes                               | DebugController/routes                          | get    | DebugController/routes                          |
| debug/app                                  | DebugController/appInfo                         | get    | DebugController/appInfo                         |
| think                                      | <Closure>                                       | get    |                                                 |
| hello/<name>                               | index/hello                                     | get    | index/hello                                     |
+--------------------------------------------+-------------------------------------------------+--------+-------------------------------------------------+
